

function tex_str = generate_latex_figure( ...
    eps_list, err_eps, bound_eps, N_fixed, ...
    N_list,   err_N,   bound_N,   eps_fixed)
% GENERATE_LATEX_FIGURE
%   Builds a pgfplots two-subfigure LaTeX block (error vs epsilon on the
%   left, error vs N on the right), in the same style as the reference
%   document, with a single "Random" curve and the per-trial theorem
%   bound curve on each panel.

tex_str = sprintf([ ...
'\\begin{figure}[htbp]\n' ...
'  \\centering\n' ...
'  \\begin{subfigure}[t]{0.48\\linewidth}\n' ...
'    \\centering\n' ...
'    \\begin{tikzpicture}\n' ...
'    \\begin{axis}[\n' ...
'        width=0.98\\linewidth,\n' ...
'        height=5.0cm,\n' ...
'        grid=both,\n' ...
'        grid style={dotted},\n' ...
'        minor tick num=0,\n' ...
'        enlarge x limits=false,\n' ...
'        xlabel near ticks,\n' ...
'        ylabel near ticks,\n' ...
'        xlabel style={font=\\tiny},\n' ...
'        ylabel style={font=\\tiny},\n' ...
'        tick label style={font=\\tiny},\n' ...
'        legend style={\n' ...
'            font=\\tiny,\n' ...
'            draw=none,\n' ...
'            fill=none,\n' ...
'            at={(0.02,0.98)},\n' ...
'            anchor=north west,\n' ...
'        },\n' ...
'        xmode=log,\n' ...
'        ymode=log,\n' ...
'        log basis x=10,\n' ...
'        xlabel={$\\varepsilon$},\n' ...
'        ylabel={$\\|S-\\tilde S\\|_2$},\n' ...
'        title={\\tiny{Error versus $\\varepsilon$ ($N=%d$)}},\n' ...
'    ]\n' ...
'    \\addplot[cyan!60!black, thick, mark=*] coordinates{\n' ...
'    %s\n' ...
'    }; \\addlegendentry{Random}\n' ...
'    \\addplot[black, dashed, thick, mark=none] coordinates{\n' ...
'    %s\n' ...
'    }; \\addlegendentry{$2\\sqrt{w_{lo}^2+w_{up}^2}\\varepsilon$}\n' ...
'    \\end{axis}\n' ...
'    \\end{tikzpicture}\n' ...
'\\caption{For $N=%d$ we report how the block encoding error increases with $\\varepsilon$ ranging from %.1e to %.1e.\n' ...
'        \\label{fig:first}}\n' ...
'  \\end{subfigure}\n' ...
'  \\hfill\n' ...
'  \\begin{subfigure}[t]{0.48\\linewidth}\n' ...
'    \\centering\n' ...
'    \\begin{tikzpicture}\n' ...
'    \\begin{axis}[\n' ...
'        width=0.95\\linewidth,\n' ...
'        height=5.0cm,\n' ...
'        grid=both,\n' ...
'        grid style={dotted},\n' ...
'        minor tick num=0,\n' ...
'        enlarge x limits=false,\n' ...
'        xlabel near ticks,\n' ...
'        ylabel near ticks,\n' ...
'        xlabel style={font=\\tiny},\n' ...
'        ylabel style={font=\\tiny},\n' ...
'        tick label style={font=\\tiny},\n' ...
'        legend style={\n' ...
'            font=\\tiny,\n' ...
'            draw=none,\n' ...
'            fill=none,\n' ...
'            at={(0.55,0.85)},\n' ...
'            anchor=north east,\n' ...
'        },\n' ...
'        xmode=log,\n' ...
'        log basis x=2,\n' ...
'        xmin=%d, xmax=%d,\n' ...
'        xtick={%s},\n' ...
'        xticklabels={%s},\n' ...
'        xlabel={$N$},\n' ...
'        ylabel={$\\|S-\\tilde S\\|_2$},\n' ...
'        title={\\tiny{Error versus $N$ ($\\varepsilon=%.1e$)}},\n' ...
'        scaled y ticks=false,\n' ...
'    ]\n' ...
'    \\addplot[cyan!60!black, thick, mark=*] coordinates{\n' ...
'    %s\n' ...
'    }; \\addlegendentry{Random}\n' ...
'    \\addplot[black, dashed, thick, mark=none] coordinates{\n' ...
'    %s\n' ...
'    }; \\addlegendentry{$2\\sqrt{w_{lo}^2+w_{up}^2}\\varepsilon$}\n' ...
'    \\end{axis}\n' ...
'    \\end{tikzpicture}\n' ...
'            \\caption{For different values of $N$ and for $\\varepsilon = %.1e$, we report the actual errors of the encoding for the Random generator case, together with the theorem bound $2\\sqrt{w_{lo}^2+w_{up}^2}\\varepsilon$.}\n' ...
'        \\label{fig:second}\n' ...
'  \\end{subfigure}\n' ...
'  \\caption{Unsymmetric semiseparable reconstruction error scaling: sensitivity to $\\varepsilon$ (left) and $N$ (right).}\n' ...
'  \\label{fig:err_combined_unsymm}\n' ...
'\\end{figure}\n' ...
], ...
    N_fixed, coords_str(eps_list,err_eps), coords_str(eps_list,bound_eps), ...
    N_fixed, min(eps_list), max(eps_list), ...
    min(N_list), max(N_list), ...
    strjoin(arrayfun(@(v)sprintf('%d',v),N_list,'UniformOutput',false),','), ...
    strjoin(arrayfun(@(v)sprintf('%d',v),N_list,'UniformOutput',false),','), ...
    eps_fixed, ...
    coords_str(N_list,err_N), coords_str(N_list,bound_N), ...
    eps_fixed);

end
